### ISSUE TITLE
JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by tjcelaya** [joyent/manta-archiver#11]
```
Exception in thread "main" java.lang.SecurityException: JCE cannot authenticate the provider BC
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:113)
	at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:303)
	at com.joyent.manta.client.crypto.SecretKeyUtils.generate(SecretKeyUtils.java:69)
	at com.joyent.manta.archiver.MantaArchiverCLI$GenerateKey.run(MantaArchiverCLI.java:298)
	at com.joyent.manta.archiver.MantaArchiverCLI.main(MantaArchiverCLI.java:135)
Caused by: java.util.jar.JarException: file:/jar/manta-archiver-1.0.0-SNAPSHOT.jar has unsigned entries - com/joyent/manta/archiver/DirectoryUpload.class
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:500)
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:361)
	at javax.crypto.JarVerifier.verify(JarVerifier.java:289)
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:159)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:185)
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:109)
	... 4 more
```

**Comment by tjcelaya** [comment]
Duplicates #3
