### ISSUE TITLE
JCE cannot authenticate the provider BC - error when generating key

### ISSUE THREAD

**Issue by dekobon** [joyent/manta-archiver#3]
```
java -jar target/manta-archiver-1.0.0-SNAPSHOT.jar generate-key 'AES' 128 ./uber-key
Exception in thread "main" java.lang.SecurityException: JCE cannot authenticate the provider BC
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:113)
	at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:303)
	at com.joyent.manta.client.crypto.SecretKeyUtils.generate(SecretKeyUtils.java:69)
	at com.joyent.manta.archiver.MantaArchiverCLI$GenerateKey.run(MantaArchiverCLI.java:273)
	at com.joyent.manta.archiver.MantaArchiverCLI.main(MantaArchiverCLI.java:124)
Caused by: java.util.jar.JarException: file:/Users/elijah/Development/Joyent/manta-archiver/target/manta-archiver-1.0.0-SNAPSHOT.jar has unsigned entries - com/joyent/manta/archiver/FileUpload.class
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:500)
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:361)
	at javax.crypto.JarVerifier.verify(JarVerifier.java:289)
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:159)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:185)
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:109)
	... 4 more
```

**Comment by tjcelaya** [comment]
Resolved by #10 with the switch away from maven-shade-plugin.

This is a pretty big issue. If I may be frank, I would not have made the repo public without resolving something as crucial as "does encryption work" given this project exists entirely because [manta-sync](https://github.com/bahamas10/node-manta-sync) does not support client-side encryption.
